Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -28,6 +28,14 @@ jobs:
     - name: Build the React app
       run: npm run build
 
+    # Ellenőrzés, hogy létezik-e a build mappa
+    - name: Check if build directory exists
+      run: |
+        if [ ! -d "build" ]; then
+          echo "Error: Build directory does not exist."
+          exit 1
+        fi
+
     # Production branch frissítése
     - name: Deploy to production branch
       run: |
